[project]
name = "ai-spike-token-optimisation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
    "anthropic==0.21.0",
    "bert-score==0.3.13",
    "ipykernel==7.1.0",
    "llmlingua==0.2.0",
    "matplotlib==3.10.8",
    "nltk==3.8.0",
    "numpy==2.4.1",
    "openai==1.0.0",
    "pandas==3.0.0",
    "python-dotenv==1.0.0",
    "ruff==0.14.14",
    "seaborn==0.13.2",
    "taskipy==1.14.1",
    "tiktoken==0.12.0",
]

[tool.taskipy.tasks]
lint = "uv run ruff format . --check && uv run ruff check ."
create-kernel = "ipython kernel install --user --env VIRTUAL_ENV $(pwd)/.venv --name=ai-spike-token-optimisation"
